version: "3.8"

services:
    db:
        image: postgres:16.0
        container_name: app-db
        volumes:
          - postgres_data:/var/lib/postgresql/data
        env_file: .env
        ports:
          - "5432:5432"
        healthcheck:
          test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
          interval: 10s
          timeout: 15s
          retries: 5

volumes:
  postgres_data:
